import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "./components/modules/navigation/navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    lang: "en" | "de";
  };
}) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Navigation locale={params.lang} />
        {children}
      </body>
    </html>
  );
}
